uint8 game_state
uint16 remain_time              # 比赛剩余时间
uint16 our_outpost_hp
uint16 enemy_outpost_hp
uint16 remain_bullet
uint16 enemy_sentry_hp
uint16 our_sentry_hp
uint16 our_base_hp
uint8 first_blood
float32 target_position_x
float32 target_position_y
int8 is_target_active

#机器人状态字段 IsStatusOK 节点调用
uint16 shooter_17mm_1_barrel_heat   # 枪管热量
uint16 projectile_allowance_17mm    # 弹丸剩余发弹数

uint16 enemy_hero_hp
uint16 enemy_engineer_hp
uint16 enemy_infantry_3_hp
uint16 enemy_infantry_4_hp
uint16 our_hero_hp
uint16 our_engineer_hp
uint16 our_infantry_3_hp
uint16 our_infantry_4_hp
uint16 enemy_base_hp
uint16 remain_energy
